services:
  - type: web
    name: sgm-sistema-gestao-metrologica
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/health